version: 2
updates:
- package-ecosystem: npm
  directory: "/modeler/"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Amsterdam
- package-ecosystem: npm
  directory: "/debugger/"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Amsterdam
